model:
  latent_discrete: 256
  latent_continuous: 32
  dim: 1024
  depth: 16
  heads: 8
  vae_path: "/root/latest.pt"

data:
  webdataset_url: "/root/data/train/{00001..00021}.tar"
  csv_path: "tags.txt"

training:
  image_size: 256
  batch_size: 64
  learning_rate: 0.001
  max_train_steps: 1000000
  log_every_steps: 10
  save_image_every_steps: 1000
  output_dir: "outputs_ar"
  num_workers: 4
  sample_temperature: 1.0

wandb_project: "nanoWaifu-AR"
